build: false

environment:
  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"


install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe waf configure"

test_script:
  - "%PYTHON%\\python.exe waf build --run_tests"

notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: 2P/5tzQN4ul49mJHyerfyDtTd8BsPv0UYI9EGnXGJrV9HJ8/CVfB0Su7eVmQSzH4