name: Black
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  black:
    name: Black Format
    runs-on: [self-hosted, docker]
    container:
      image: kiwicom/black
      options: --user 0:0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Run Black Check
        run: black . --check
