name: Waf Python Tests
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
    - master
  pull_request:
jobs:
  waf:
    env:
      python: python3
    name: ${{ matrix.os }} Waf
    runs-on:
    - self-hosted
    - ${{ matrix.os }}
    - builder
    steps:
    - if: runner.os == 'Windows'
      name: Rename python3 to python on Windows
      run: echo "python=python" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8
        -Append
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: ${{ env.python }} waf configure
    - name: Build
      run: ${{ env.python }} waf
    - name: Test
      run: ${{ env.python }} waf --run_tests
    strategy:
      fail-fast: false
      matrix:
        os:
        - Windows
        - Linux
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
